# Generated by Django 5.0 on 2024-02-27 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_book',
            field=models.FileField(blank=True, null=True, upload_to='pdf_book/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
